language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

services:
  - docker

notifications:
  email:
    recipients:
      - simone.mosciatti@cern.ch
      - jakob.blomer@cern.ch
    on_success: change
    on_failure: always

before_install:
  - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.7.3/cvmfs-server_2.7.3~1+ubuntu18.04_amd64.deb
  - sudo apt-get install ./cvmfs-server_2.7.3~1+ubuntu18.04_amd64.deb

script: go test -mod=vendor -v ./...
