language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
      go: master
    - os: linux
      dist: xenial
      go: master

env:
  - GO111MODULE=on

services:
  - docker

notifications:
  email:
    recipients:
      - simone.mosciatti@cern.ch
      - jakob.blomer@cern.ch
    on_success: change
    on_failure: always

before_install:
  - wget https://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-2478/cvmfs-server_2.8.0~0.2478gitacdac6f0b88f0111+ubuntu$(lsb_release -rs)_amd64.deb
  - sudo apt-get install -y ./cvmfs-server_2.8.0~0.2478gitacdac6f0b88f0111+ubuntu$(lsb_release -rs)_amd64.deb

script: go test -mod=vendor -v ./...
