language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

services:
  - docker

notifications:
  email:
    recipients:
      - simone.mosciatti@cern.ch
      - jakob.blomer@cern.ch
    on_success: change
    on_failure: always

script: go test -mod=vendor -v ./...
